package se.nrm.dina.dnakey.portal.util;

/**
 *
 * @author idali
 */
public class FastaFiles {
    
    private static final String FASTA_FILE_1 = ">Seq 1\n"
                                                + "CTTATCTTCGGGGCATGAGCCGGAATAATTGGCACAGCACTCAGCCTACTGATCCGCGCAGAACTAGGCCAACCAGGAACCCTCCTG"
                                                + "GGCGACGACCAAATTTACAACGTAATCGTCACCGCCCACGCCTTTGTAATAATCTTCTTCATGGTAATACCCATCATGATTGGAGGA"
                                                + "TTCGGCAACTGATTAGTCCCCCTAATAATCGGCGCCCCTGACATAGCATTCCCACGAATAAACAACATAAGCTTCTGACTCCTCCCA"
                                                + "CCATCATTCCTCCTCCTACTCGCCTCATCTACCGTAGAAGCTGGGGCCGGTACAGGTTGAACCGTGTACCCACCCCTAGCAGGCAAC"
                                                + "CTGGCCCACGCCGGAGCCTCAGTAGACCTAGCTATCTTCTCCCTTCACCTAGCCGGTGTCTCCTCCATCCTCGGGGCCATTAACTTC"
                                                + "ATTACCACAGCCATCAACATAAAACCCCCTGCACTCTCACAGTACCAAACCCCACTTTTCGTCTGATCGGTCCTAATTACCGCCATC"
                                                + "CTACTCCTCCTATCACTCCCTGTCCTCGCCGCCGGCATCACAATGCTACTAACCGACCGAAACCTAAACACCACATTCTTTGACCCC"
                                                + "GCCGGAGGAGGAGACCCAATCCTGTACCAACACCTATTT\n\n";

    private static final String FASTA_FILE_2 = ">Seq 2\n"
                                                + "CTAATCTTCGGTGCATGAGCTGGCATGGTCGGAACCGCCCTCAGCCTGCTTATTCGTGCAGAACTAGGCCAACCAGGAACCCTCTTG"
                                                + "GGAGATGACCAAATCTACAATGTAATCGTTACTGCTCATGCATTCGTAATAATTTTCTTCATAGTTATACCAATCATGATCGGAGGA"
                                                + "TTTGGAAATTGACTAGTCCCACTCATAATCGGCGCCCCCGACATAGCATTTCCTCGTATAAACAATATAAGCTTCTGACTACTCCCC"
                                                + "CCATCATTCCTATTATTACTAGCATCCTCTACAGTAGAAGCTGGAGCTGGCACAGGATGAACAGTATATCCACCCCTCGCCGGCAAC"
                                                + "CTAGCCCACGCAGGAGCCTCAGTAGACCTAGCTATTTTCTCCCTCCATTTAGCAGGTGTCTCCTCCATCCTAGGTGCCATTAACTTT"
                                                + "ATCACCACTGCCATTAACATAAAACCACCAGCCCTGTCCCAATACCAAACACCCCTATTTGTATGATCAGTACTCATTACCGCCGTC"
                                                + "TTACTGCTACTCTCACTCCCAGTCCTTGCTGCCGGCATCACCATGCTATTAACAGATCGTAATCTAAACACCACATTCTTTGACCCA"
                                                + "GCCGGAGGAGGAGACCCAGTCCTATACCAACATCTCTTC\n\n";


 
    private static final String FASTA_FILE_3 = ">Seq 3\n"
                                                + "CTGATTTTCGGCGCATGAGCCGGAATGGTAGGTACCGCCTTAAGCCTCCTCATCCGAGCAGAACTAGGCCAACCCGGAGCCCTCCTG"
                                                + "GGAGACGACCAAGTCTACAACGTAGTCGTCACAGCCCACGCTTTCGTAATAATCTTCTTCATAGTTATACCAATTATGATCGGAGGG"
                                                + "TTCGGAAACTGACTCGTCCCCCTAATAATCGGAGCCCCAGACATAGCATTCCCACGGATAAACAACATAAGCTTCTGACTACTCCCC"
                                                + "CCATCCTTCCTGCTACTACTAGCATCTTCTACTGTAGAAGCAGGCGTAGGAACAGGCTGAACAGTGTACCCCCCACTAGCCGGAAAC"
                                                + "CTAGCCCATGCCGGAGCTTCGGTCGACCTCGCAATCTTCTCCCTTCACCTAGCCGGTATCTCTTCAATCCTGGGGGCAATCAACTTC"
                                                + "ATCACTACAGCAATCAACATAAAACCACCTGCCCTCTCACAATACCAAACCCCTCTATTCGTCTGATCAGTCTTAATTACCGCAGTC"
                                                + "CTCCTGCTCCTGTCCCTCCCAGTCCTTGCCGCCGGCATTACAATACTACTCACGGACCGTAACCTTAACACCACATTCTTCGACCCT"
                                                + "GCTGGAGGAGGAGACCCCGTCCTATACCAACATCTCTTC\n\n";

    
    private static final String FASTA_FILE_4 = ">Seq 4\n" 
                                                + "CTACTCTTCGGAGCATGAGCAGGTATAGCCGGTACCGCCCTTAGCCTTCTTATTCGAGCAGAACTTGGCCAACCGGGGACTCTTCTT"
                                                + "GGAGACGACCAGATCTACAATGTCATCGTCACCGCCCATGCCTTCGTAATAATCTTCTTCATAGTCATACCCATTATAATCGGAGGA"
                                                + "TTTGGAAACTGACTAGTCCCCCTTATAATTGGAGCCCCAGACATAGCATTCCCCCGAATAAACAACATAAGTTTCTGATTACTCCCC"
                                                + "CCATCCTTCCTACTACTCCTGGCATCTTCCACAGTAGAAGCCGGAGTCGGAACAGGATGAACCGTTTACCCCCCCTTAGCAGGCAAC"
                                                + "CTGGCCCATGCTGGCGCCTCAGTAGACCTAGCCATCTTCTCCCTGCACCTCGCAGGTGTATCTTCCATCCTGGGGGCAATCAACTTT"
                                                + "ATCACAACAGCCATTAACATAAAACCCCCTGCCCTGTCACAATACCAAACCCCATTATTCGTGTGATCCGTACTCATCACAGCCGTA"
                                                + "CTCCTACTGCTCTCACTCCCAGTCTTAGCCGCTGGCATCACCATACTACTAACCGACCGAAATCTAAACACCACATTCTTCGACCCC"
                                                + "GCCGGAGGAGGAGACCCTATTCTCTACCAACACCTATTC\n\n";
    
    private static final String FASTA_FILE_5 = ">Seq 5\n"
                                                + "CTAGTCTTCGGTGCATGGGCCGGCATAGTAGGCACAGCCCTCAGCCTCCTAATTCGGGCAGAACTAGGACAACCAGGAACCCTTCTA"
                                                + "GGGGACGACCAGATTTACAACGTAATTGTCACTGCCCACGCCTTTGTAATAATTTTCTTCATGGTAATACCCATCATGATTGGCGGA"
                                                + "TTTGGAAACTGACTAGTCCCCCTCATAATCGGAGCCCCGGACATAGCATTTCCCCGCATAAATAACATAAGCTTCTGACTACTTCCC"
                                                + "CCCTCCTTCCTATTACTGCTAGCATCTTCCACAGTTGAAGCTGGAGCAGGCACAGGATGGACTGTCTACCCACCACTGGCCAGCAAC"
                                                + "ATAGCCCACGCCGGGGCCTCAGTTGATCTGGCCATTTTTTCGCTCCACTTAGCAGGTATCTCATCAATCCTCGGGGCAATCAACTTC"
                                                + "ATTACAACCGCCATCAACATAAAACCCCCGGCCCTGTCACAATACCAAACACCCCTATTTGTATGATCAGTCTTCATCACCGCAATC"
                                                + "CTACTTCTGCTATCCCTCCCAGTACTAGCCGCTGGCATTACCATGCTCCTAACTGACCGAAACCTAAACACCACATTCTTTGATCCT"
                                                + "GCCGGAGGGGGCGACCCTGTCCTGTACCAGCACCTTTTC\n\n";
     
    
    
    private static final String FASTA_FILE_6 = ">Seq 6\n"
                                                + "TCACCCATCGCCAGATAGATTGCGCTGGCACCGCAGATCAGACCAATCCAGCCGGCAAAGTGGATGATTGCGGCGTTACC"
                                                + "GGCAATGTTACCGATCGCCAGCAGGGCAAACAGCACGGTCAGGCTAAAGAAAACGAATTGCAGAACGCGTGCGCCTTTCA"
                                                + "GCGTGCCGAAGAACATAAACAGCGTAAATACGCCCCACAGACCCAGGTAGACACCAAGGAACTGTGCATTTGGCGCATCG"
                                                + "GTCAGACCCAGTTTCGGCATCAGCAGAATCGCAACCAGCGTCAGCCAGAAAGAACCGTAAGAGGTGAATGCGGTTAAACC"
                                                + "GAAAGTGTTGCCTTTTTTGTACTCCAGCAGACCAGCAAAAATTTGCGCGATGCCGCCGTAGAAAATGCCCATGGCAAGAAT\n\n";
    
    
    private static FastaFiles instance = null;

    public static synchronized FastaFiles getInstance() {
        if (instance == null) {
            instance = new FastaFiles();
        }
        return instance;
    }
    
    public String getSequence(int count) {
        
         switch (count) {
            case 1:     
                return FASTA_FILE_1; 
            case 2:     
                return FASTA_FILE_2; 
            case 3:     
                return FASTA_FILE_3; 
            case 4:     
                return FASTA_FILE_4; 
            case 5:     
                return FASTA_FILE_5; 
            case 6:     
                return FASTA_FILE_6;  
            default:    
                return null; 
         }
    }
}
